FROM python:3

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install nodejs
RUN npm install -g serverless

RUN pip install -U pytest
RUN pip install Pillow

RUN pip install chromeless==0.2.9
RUN pip install chromeless==0.3.0

COPY example.py .
COPY pip_install.py .
COPY __version__.py .
COPY Makefile .
COPY serverless.yml .
